Print Prusti version, clarify error message
viperproject/prusti-dev pull request #1160
Opened 2022-09-20 08:50 UTC by fpoli

2022-09-20 16:02 UTC, fpoli commented on prusti-interface/src/specs/checker/version_checks.rs
> +                        `prusti-contracts`/`prusti-specs` is '{min_prusti_version}'! \
@JonasAlaif if this change is consistent with the use cases that you looked at, could you `bors r+` the PR?

2022-09-20 20:47 UTC, JonasAlaif requested changes, later dismissed

2022-09-20 20:47 UTC, JonasAlaif commented on prusti-interface/src/specs/checker/version_checks.rs
> +                        `prusti-contracts`/`prusti-specs` is '{min_prusti_version}'! \
So the thing is that `min_prusti_version` is a config flag - it happens to be set by `prusti-contracts` in a `Prusti.toml` but could be set by any other crate. This issue is too specific

2022-09-21 11:45 UTC, fpoli commented
bors r+

2022-09-22 08:00 UTC, merged