Port testcases to new syntax
viperproject/prusti-dev pull request #130
Opened 2020-08-16 21:35 UTC by karlosss

2020-08-17 05:30 UTC, vakaras requested changes
I think we will merge this PR only when the tests will actually start passing.

2020-08-17 05:30 UTC, vakaras commented on prusti/tests/verify/pass/loop-invs/framing_after_break.rs
> +        invariant!(x == 123);
Is this test executed? This should be `body_invariant!`.

2020-08-17 05:30 UTC, vakaras commented on prusti/tests/verify/pass/loop-invs/framing_after_break.rs
> +        invariant!(x == 123);
Same here.

2020-08-17 05:30 UTC, vakaras commented on prusti/tests/verify/pass/loop-invs/initialize_in_loop_condition.rs
> +        invariant!(*x < 55);
And here.

2020-08-17 05:30 UTC, vakaras commented on prusti/tests/verify/pass/loop-invs/negate_loop_condition.rs
> +        invariant!(g); // Ok, as the loop invariant is not reached after `g = false`
And here.

2020-08-17 05:30 UTC, vakaras commented on prusti/tests/verify/pass/loop-invs/result_in_guard.rs
> +        invariant!(0 <= i && i < 10);
And here.

2020-08-17 05:30 UTC, vakaras commented on prusti/tests/verify/pass/quick/fibonacci.rs
> +    invariant!(_ghost_counter >= 1);
These should be `body_invariant!` and inside the loop body.

2020-08-17 05:30 UTC, vakaras commented on prusti/tests/verify/pass/quick/fibonacci.rs
> +    body_invariant!(iter.valid());
Same here.

2020-08-17 05:30 UTC, vakaras commented on prusti/tests/verify/pass/quick/knapsack.rs
> +    body_invariant!(max_weight + 1 == best_value.weight_len());
These should be inside the loop body.

2020-08-17 05:30 UTC, vakaras commented on prusti/tests/verify/pass/quick/knapsack.rs
> +        body_invariant!(items.len() + 1 == best_value.item_len());
Same here.

2020-08-17 05:30 UTC, vakaras commented on prusti/tests/verify/pass/quick/knapsack.rs
> +    body_invariant!(items.len() + 1 == best_value.item_len());
And here.

2020-08-17 05:30 UTC, vakaras commented on prusti/tests/verify/pass/quick/marker-traits.rs
> +#[trait_invariant(self.d1 == self.d2)]
Could you add a comment that `trait_invariant` currently is not even parsed so that people do not get confused?

cc @cmatheja

2020-08-17 05:30 UTC, vakaras commented on prusti/tests/verify/pass/quick/mut-borrows-binary-search.rs
> -    #[ensures="result >= 0"]
When overflow checks are disabled, this postcondition is still needed.

2020-08-17 05:30 UTC, vakaras commented on prusti/tests/verify/pass/quick/mut-borrows-binary-search.rs
> +    body_invariant!(0 <= size);
Should be inside a loop.

2020-08-17 05:30 UTC, vakaras commented on prusti/tests/verify/pass/quick/nll-rfc-case1.rs
> -    #[ensures="result >= 0"]
Same here.

2020-09-16 12:49 UTC, Aurel300 commented
I guess some of this is deprecated by #160 @fpoli ?

2020-09-16 13:32 UTC, fpoli commented
> I guess some of this is deprecated by #160 @fpoli ?

The tests under `prusti/tests` probably yes, but there are various other changes that I don't fully understand. Moveover, this PR has `rustc-update` as target branch, which I thought could be deleted. Do you know what's the status here @vakaras?

2020-09-16 14:22 UTC, karlosss commented
IIRC, originally the idea was that for every group of testcases ported to the new version of Prusti, a PR will be done; however, the changes made to the codebase might have been quite significant, therefore we decided to create a separate branch for these purposes. But later it turned out that the state of the codebase is such that I am unable to productively work on it. So maybe as of now, the branch is indeed useless.

2020-09-20 17:18 UTC, vakaras commented
> > I guess some of this is deprecated by #160 @fpoli ?
> 
> The tests under `prusti/tests` probably yes, but there are various other changes that I don't fully understand. Moveover, this PR has `rustc-update` as target branch, which I thought could be deleted. Do you know what's the status here @vakaras?

I think we should cherry-pick https://github.com/viperproject/prusti-dev/commit/17efa628a0aa9404962debd7320008dd55fc823c if it is not already redone (it fixes the recognition which blocks are spec blocks).

2020-09-22 10:23 UTC, fpoli commented
I think that with #176 we took everything we could from this PR. So, I'm closing.

2020-09-22 10:23 UTC, closed without merging