Disambiguate between Generics in extern_spec rewriter
viperproject/prusti-dev pull request #731
Opened 2021-10-27 15:39 UTC by JonasAlaif

Closes #626. The issue was caused by blindly using `syn::Generics` (generic _parameters_) as `syn::GenericArgument` (generic _arguments_).

2021-10-27 16:05 UTC, Aurel300 commented on prusti-specs/src/extern_spec_rewriter.rs
> +                syn::parse_quote!{ core::marker::PhantomData<#ident> }
Minor thing to prevent user-defined `core` imports or something…
```suggestion
                syn::parse_quote!{ ::core::marker::PhantomData<#ident> }
```
Also in L243.

2021-10-27 16:09 UTC, Aurel300 commented on prusti-specs/src/extern_spec_rewriter.rs
> +type CommaPunct<T> = syn::punctuated::Punctuated<T, syn::token::Comma>;
```suggestion
type CommaPunct<T> = syn::punctuated::Punctuated<T, syn::Token![,]>;
```

2021-10-27 16:11 UTC, Aurel300 commented on prusti-specs/src/extern_spec_rewriter.rs
> +    new_struct.fields = syn::Fields::Unnamed( syn::parse_quote!{ (#fields) } );
Does it work if you define `fields` as a `Vec<syn::Field>` and then:
```suggestion
    new_struct.fields = syn::Fields::Unnamed( syn::parse_quote!{ (#(#fields),*) } );
```
If so, you can get rid of the `CommaPunct` bit, and just have `let mut fields = vec![];`

2021-10-27 16:13 UTC, Aurel300 commented on prusti-specs/src/extern_spec_rewriter.rs
> +    syn::parse_quote!{ < #args > }
(Same comment as above about `Vec`)

2021-10-27 16:14 UTC, Aurel300 commented on prusti-specs/src/extern_spec_rewriter.rs
> +        let res: syn::GenericArgument = syn::parse_quote!{#ts}; res
A `syn::parse_quote!{ #ts }` should be equivalent to `syn::parse(ts)` (or `parse2` depending on which type it is).
```suggestion
        syn::parse::<syn::GenericArgument>(ts).unwrap()
```

2021-10-27 16:16 UTC, Aurel300 requested changes
Looks good! Small improvements might be possible, and more importantly: please add a test.

2021-10-27 16:27 UTC, JonasAlaif commented on prusti-specs/src/extern_spec_rewriter.rs
> +    new_struct.fields = syn::Fields::Unnamed( syn::parse_quote!{ (#fields) } );
Hmm do you think it's more clear like you suggest? I could just import `syn::punctuated::Punctuated` and use `Punctuated<syn::Field, syn::Token![,]>` as the type of `fields` - that way we also do not need the type alias, but avoid this `parse_quote` black magic?

2021-10-27 19:42 UTC, Aurel300 commented on prusti-specs/src/extern_spec_rewriter.rs
> +    new_struct.fields = syn::Fields::Unnamed( syn::parse_quote!{ (#fields) } );
Sure, both save space a bit. I think this type of interpolation is used in other places already, so it wouldn't be too out of place :)

2021-10-29 09:15 UTC, Aurel300 commented on prusti-specs/src/extern_spec_rewriter.rs
> +    let mut fields = Vec::<syn::Field>::new();
```suggestion
    let mut fields = vec![];
```

2021-10-29 09:16 UTC, Aurel300 commented on prusti-tests/tests/verify/pass/extern-spec/trait-bounds.rs
> +// ignore-test None of this Generics stuff currently works with Prusti...
Ok, could we then have a UI test as well? :D

2021-11-05 14:09 UTC, merged