Add Lifetime Encoding Function Specifications
viperproject/prusti-dev pull request #997
Opened 2022-05-09 12:22 UTC by pascal-huber

- [ ] Inhale access to lifetimes which are live on entry
 - [ ] Assume subset relations of lifetimes on entry

2022-05-23 10:27 UTC, vakaras commented on vir/defs/high/ast/predicate.rs
> +#[display(fmt = "LifetimeToken")]
```suggestion
#[display(fmt = "acc(LifetimeToken({}), {})", lifetime, rd_perm)]
```

2022-05-23 10:30 UTC, pascal-huber commented on vir/defs/high/ast/predicate.rs
> +#[display(fmt = "LifetimeToken")]
done

2022-05-23 11:05 UTC, vakaras requested changes
Overall looks good, but before merging I would like two changes to be made:

1. Lifetime tokens inside a function should be inhaled not with a full lifetime, but with some unknown positive permission amount `q`. This will require to use that permission amount when encoding all `rd_perm`s: instead of `acc(..., 1/rd_perm)` it should be `acc(..., q/rd_perm)`.
2. Instead of `LifetimeIncluded` statement it should be an expression `included(lft1, intersect(lft2, lft3))` or something like that.

2022-05-23 11:05 UTC, vakaras commented on vir/defs/middle/ast/statement.rs
> +#[display(fmt = "lifetime_included({}, {})", lhs, "display::cjoin(rhs)")]
```suggestion
// TODO: Make LifetimeIncluded an Expression and use Assert/Assume Statement
// We should use BuiltinFuncApp for this: https://github.com/viperproject/prusti-dev/blob/master/vir/defs/high/ast/expression.rs#L245-L252
```

2022-05-23 11:05 UTC, vakaras commented on vir/defs/high/ast/statement.rs
> +// TODO: Make LifetimeIncluded an Expression and use Assert/Assume Statement
```suggestion
// TODO: Make LifetimeIncluded an Expression and use Assert/Assume Statement
// We should use BuiltinFuncApp for this: https://github.com/viperproject/prusti-dev/blob/master/vir/defs/high/ast/expression.rs#L245-L252
```

2022-05-23 11:05 UTC, vakaras commented on prusti-viper/src/encoder/mir/procedures/encoder/scc.rs
> +// source: https://rosettacode.org/wiki/Tarjan#Rust
Please add a comment mentioning the license.

2022-05-23 11:05 UTC, vakaras commented on prusti-viper/src/encoder/high/procedures/interface.rs
> +        // println!("end of encode_procedure_core_proof");
```suggestion
```

2022-05-23 11:05 UTC, vakaras commented on prusti-viper/src/encoder/middle/core_proof/lifetimes/interface.rs
> +        let function_call = vir_low::Expression::domain_function_call(
This n-ary function call looks strange: what axioms do you use to define it? What is the advantage compared to using the binary intersection function?

2022-05-23 11:05 UTC, vakaras commented on prusti-viper/src/encoder/mir/procedures/encoder/lifetimes.rs
> +            let inhale_statement = self.encode_inhale_lifetime_token(lifetime.clone(), 1)?;
```suggestion
            let inhale_statement = self.encode_inhale_lifetime_token(lifetime.clone(), rd)?;
```
This should be not `1`, but some unknown positive permission amount. You can use an unconstrained variable of type [`MPerm`](https://github.com/viperproject/prusti-dev/blob/15f651bc3cfffd78583b3862f2be9e0ad9b4feee/vir/defs/high/ast/ty.rs#L14-L15) for this.

2022-05-23 11:05 UTC, vakaras commented on prusti-viper/src/encoder/mir/procedures/encoder/mod.rs
> +
```suggestion
```

2022-05-23 11:05 UTC, vakaras commented on prusti-viper/src/encoder/mir/procedures/encoder/mod.rs
> +    let function_call_ctr: &mut usize = &mut 0;
Why is this a mutable reference?

2022-05-23 11:14 UTC, pascal-huber commented on prusti-viper/src/encoder/mir/procedures/encoder/mod.rs
> +    let function_call_ctr: &mut usize = &mut 0;
No reason - changed it to `let function_call_ctr: usize = 0;`.

2022-05-23 11:15 UTC, pascal-huber commented on prusti-viper/src/encoder/mir/procedures/encoder/mod.rs
> +
done

2022-05-23 11:34 UTC, pascal-huber commented on prusti-viper/src/encoder/high/procedures/interface.rs
> +        // println!("end of encode_procedure_core_proof");
ups, done

2022-05-23 11:38 UTC, pascal-huber commented on prusti-viper/src/encoder/middle/core_proof/lifetimes/interface.rs
> +        let function_call = vir_low::Expression::domain_function_call(
The idea was that if I construct a binary operation here, I will have to destruct it again later to create the function call. It should translate to the domain function `intersect`.

2022-05-23 11:45 UTC, pascal-huber commented on prusti-viper/src/encoder/mir/procedures/encoder/scc.rs
> +// source: https://rosettacode.org/wiki/Tarjan#Rust
done

2022-05-23 11:47 UTC, pascal-huber commented on vir/defs/high/ast/statement.rs
> +// TODO: Make LifetimeIncluded an Expression and use Assert/Assume Statement
added comment

2022-05-23 11:50 UTC, pascal-huber commented on vir/defs/middle/ast/statement.rs
> +#[display(fmt = "lifetime_included({}, {})", lhs, "display::cjoin(rhs)")]
I assume removing `fmt` in the suggestion is a mistake? I added the comments.

2022-05-23 11:58 UTC, pascal-huber commented
> Overall looks good, but before merging I would like two changes to be made:
> 
>     1. Lifetime tokens inside a function should be inhaled not with a full lifetime, but with some unknown positive permission amount `q`. This will require to use that permission amount when encoding all `rd_perm`s: instead of `acc(..., 1/rd_perm)` it should be `acc(..., q/rd_perm)`.

Ok, can do this. Is there an advantage of using an unconstrained permission amount?

> 
>     2. Instead of `LifetimeIncluded` statement it should be an expression `included(lft1, intersect(lft2, lft3))` or something like that.

Currently this is done in `into_low/cfg.rs`. It produces for example:

```
  inhale included$(lft_0$snapshot$0, intersect$3(lft_1$snapshot$0, lft_2$snapshot$0, lft_3$snapshot$0))
```

2022-05-25 08:54 UTC, pascal-huber commented on prusti-viper/src/encoder/middle/core_proof/lifetimes/interface.rs
> +        let function_call = vir_low::Expression::domain_function_call(
solved by using `BuiltinFuncApp`

2022-05-25 08:54 UTC, pascal-huber commented on prusti-viper/src/encoder/mir/procedures/encoder/lifetimes.rs
> +            let inhale_statement = self.encode_inhale_lifetime_token(lifetime.clone(), 1)?;
done

2022-05-25 10:08 UTC, vakaras commented on vir/defs/high/ast/expression.rs
> +impl Expression {
This should be in [this file](https://github.com/viperproject/prusti-dev/blob/master/vir/defs/high/operations_internal/expression.rs).

2022-05-25 10:09 UTC, vakaras commented on vir/src/low/operations/ty.rs
> +                println!("-- get_type --");
Please remove debug output.
```suggestion
```

2022-05-25 10:10 UTC, vakaras approved these changes
Overall looks good. Once the two minor things are addressed, I will merge.

2022-05-25 10:13 UTC, pascal-huber commented on vir/src/low/operations/ty.rs
> +                println!("-- get_type --");
missed that one, done

2022-05-25 10:13 UTC, pascal-huber commented on vir/defs/high/ast/expression.rs
> +impl Expression {
moved

2022-05-25 10:28 UTC, vakaras approved these changes
bors r+

2022-05-25 14:02 UTC, vakaras commented
bors retry

2022-05-25 14:38 UTC, vakaras commented
bors r-

2022-05-25 14:38 UTC, vakaras commented
bors r+

2022-05-25 14:55 UTC, vakaras commented
bors cancel

2022-05-25 14:56 UTC, vakaras commented
bors r+

2022-05-25 14:57 UTC, vakaras commented
bors cancel

2022-05-25 15:03 UTC, vakaras commented
bors r+

2022-05-25 19:49 UTC, merged